name: Step 2, Commit a file

# This step listens for the learner to commit a file to branch `my-first-branch`.
# This workflow updates from step 2 to step 3.

# This action will run every time there's a push to `my-first-branch`.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - my-first-branch

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  get_file_created:
    name: Check created filename
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "created_filenames=$(ls .)" >> $GITHUB_OUTPUT
    outputs:
      created_filenames: ${{ steps.get_step.ouputs.created_filenames }}

  get_file_content:
    name: Check contents of profile.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "profile_content=$(cat ./PROFILE.md)" >> $GITHUB_OUTPUT
    outputs:
      profile_content: ${{ steps.get_step.ouputs.profile_content }}
        
  on_commit_a_file:
    name: On commit a file
    needs: [get_current_step, get_file_created, get_file_content]

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 2.
    # 3. PROFILE.md file is created
    # 4. content is added to created file
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2 
          && github.ref_type == 'branch'
          && github.ref_name == 'my-first-branch' 
          && needs.get_file_created.outputs.created_filenames == contains(needs.get_file_created.outputs.created_filenames, 'PROFILE.md')
          && needs.get_file_content.outputs.profile_content != ''
          }}}}

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      # In README.md, switch step 2 for step 3.
      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: my-first-branch
